
---
- name: Install and configure MYSQL server in ubuntu
  hosts: all  # Replace "all" with the name of your target hosts or group

  tasks:
    - name: Install MYSQL server
      apt:
        name: mysql-server
        state: present  # Make sure the package is installed
    
    - name: Start MYSQL service
      service:
        name: mysql
        state: started
        enabled: yes  # Make sure the service is started on boot
    
    - name: Set MYSQL root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"  # Replace with your desired root password
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock  # Replace with the appropriate path for your system
  
  vars:
    mysql_root_password: "mySecurePassword"  # Replace with your desired root password