
---
- name: Configure MYSQL server in Ubuntu
  hosts: all
  become: yes
  vars:
    mysql_root_password: "changeme" #change this to your desired root password
  tasks:
    - name: Install MYSQL server
      apt:
        name: mysql-server
        state: present
    - name: Configure MYSQL root password
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password'
        value: '{{ mysql_root_password }}'
        vtype: password
    - name: Configure MYSQL root password (again)
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password_again'
        value: '{{ mysql_root_password }}'
        vtype: password
    - name: Restart MYSQL service
      service:
        name: mysql
        state: restarted
    - name: Create MYSQL database
      mysql_db:
        name: mydatabase #change this to your desired database name
        state: present
    - name: Create MYSQL user
      mysql_user:
        name: myuser #change this to your desired username
        password: "{{ mysql_root_password }}"
        priv: '*.*:ALL'
        host: localhost
