
---
- hosts: 3.87.87.185
  become: true
  tasks:
    - name: Get memory status
      command: free -m
      register: memory_status
      when: ansible_distribution == "Ubuntu"
    - name: Print memory status
      debug:
        msg: "{{ memory_status.stdout_lines }}"