
---
- name: Get Memory Status
  hosts: 3.87.87.185
  tasks:
    - name: Check Memory Status
      command: free -m
      register: memory_status
      become: true
      become_user: root
    - name: Display Memory Status
      debug:
        msg: "The current memory status in Ubuntu is {{ memory_status.stdout }}"