---
- name: Install HTTP Service (Apache) on Ubuntu
  hosts: all
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2 web server
      apt:
        name: apache2
        state: present

    - name: Enable Apache2 HTTP module
      command: a2enmod rewrite
      notify:
        - Restart Apache

    - name: Create a default web page
      copy:
        dest: /var/www/html/index.html
        content: "<html><body><h1>Welcome to Apache on Ubuntu!</h1></body></html>"

    - name: Start and enable Apache2 service
      systemd:
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
