
---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    
    - name: Enable Apache at boot
      service:
        name: apache2
        enabled: yes
        state: started