
---
- name: Install Apache Web Server
  hosts: all
  become: yes
  tasks:
    - name: Install Apache HTTP server
      apt:
        name: apache2
        update_cache: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3
    
    - name: Ensure Apache is enabled
      service:
        name: apache2
        enabled: yes
    
    - name: Start Apache service
      service:
        name: apache2
        state: started