
---
- name: Install Apache Web Server
  hosts: all
  become: true
  tasks:
    - name: Install Apache HTTP server package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is enabled
      service:
        name: apache2
        enabled: yes

    - name: Start Apache service
      service:
        name: apache2
        state: started