
---
- name: Install Apache Web Server
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
      become: true

    - name: Enable Apache
      service:
        name: apache2
        enabled: yes
        state: started
      become: true

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started