
---
- name: Install Apache HTTP server on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install Apache HTTP server
      apt:
        name: apache2
        state: latest
    
    - name: Ensure Apache is enabled
      service:
        name: apache2
        enabled: yes
    
    - name: Start Apache
      service:
        name: apache2
        state: started