
---

- name: Install Apache Web Server
  hosts: all
  become: true
  tasks:
    - name: Install Apache HTTP server
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is enabled
      service:
        name: apache2
        enabled: yes
        state: started
      when: ansible_os_family == "Debian"

    - name: Install Apache HTTP server
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Ensure Apache is enabled
      service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"