---
- name: Install Apache HTTP Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install Apache HTTP Server
      apt: name=apache2 state=present

    - name: Ensure Apache is enabled
      service: name=apache2 enabled=yes

    - name: Start Apache
      service: name=apache2 state=started