
---
- hosts: 3.87.87.185
  become: yes
  tasks:
    - name: Install cron package
      apt:
        name: cron
        state: present
      become: yes
    - name: Create cron job file
      copy:
        content: "0 0 * * * <command>" # Replace <command> with desired maintenance command
        dest: /etc/cron.d/maintenance
        owner: root
        group: root
        mode: 0644
      become: yes
      notify:
        - restart cron
    - name: Ensure cron service is running
      service:
        name: cron
        state: started
        enabled: yes
      become: yes
  handlers:
    - name: restart cron
      service:
        name: cron
        state: restarted