---
- name: Set Up Cron Jobs for Regular Maintenance
  hosts: all
  become: true
  vars:
    cron_jobs:
      - name: "Daily Backup"
        job: "/path/to/backup_script.sh"
        minute: "0"
        hour: "0"
        day: "*"
        month: "*"
        weekday: "*"
      - name: "Weekly Cleanup"
        job: "/path/to/cleanup_script.sh"
        minute: "0"
        hour: "0"
        day: "7"
        month: "*"
        weekday: "*"
  tasks:
    - name: Install Cron Package
      apt:
        name: cron
        state: present
    - name: Copy Backup Script
      copy:
        src: backup_script.sh
        dest: /path/to/backup_script.sh
        mode: 0755
    - name: Copy Cleanup Script
      copy:
        src: cleanup_script.sh
        dest: /path/to/cleanup_script.sh
        mode: 0755
    - name: Add Cron Jobs
      cron:
        name: "{{ item.name }}"
        job: "{{ item.job }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour