
---
- name: Set Up Cron Jobs for Regular Maintenance
  hosts: all
  become: yes
  
  tasks:
    - name: Create a cron job for regular maintenance
      cron:
        name: Regular Maintenance
        minute: "0"
        hour: "0"
        job: "maintenance_script.sh"
        state: present
    
    - name: Copy maintenance script to remote server
      copy:
        src: maintenance_script.sh
        dest: /home/user/maintenance_script.sh
        mode: 0755
    
    - name: Create a log directory
      file:
        path: /var/log/maintenance
        state: directory
    
    - name: Add log rotation for maintenance logs
      copy:
        src: logrotate.conf
        dest: /etc/logrotate.d/maintenance
        mode: 0644
    
    - name: Restart cron service
      service:
        name: cron
        state: restarted