
---
- name: Set Up Cron Jobs for Regular Maintenance
  hosts: all
  tasks:
    - name: Create cron job directory
      file:
        path: /etc/cron.d
        state: directory
        mode: 0755

    - name: Create cron job file
      copy:
        dest: /etc/cron.d/maintenance
        content: "0 0 * * * root /usr/bin/maintenance.sh"
        owner: root
        group: root
        mode: 0644

    - name: Create maintenance script
      copy:
        dest: /usr/bin/maintenance.sh
        content: |
          #!/bin/bash
          # Script for regular maintenance tasks
          # Add tasks here
          echo "Maintenance tasks completed"
        owner: root
        group: root
        mode: 0755