
---
- hosts: 3.87.87.185
  become: true
  vars:
    username: vigil
  tasks:
    - name: Create username
      user:
        name: "{{ username }}"
        state: present
        createhome: yes
        shell: /bin/bash
        update_password: on_create
        password_lock: yes
        groups: sudo
      register: user_created
    - name: Print username created
      debug:
        msg: "Username {{ username }} created successfully!"