
---
- hosts: 3.87.87.185
  become: true
  vars:
    username: testuser
    groupname: testgroup
  tasks:
    - name: Check if group exists
      command: getent group {{ groupname }}
      register: group_check
      ignore_errors: yes
      changed_when: false
      failed_when: false

    - name: Create group if it doesn't exist
      command: groupadd {{ groupname }}
      when: group_check.rc != 0

    - name: Check if user exists
      command: getent passwd {{ username }}
      register: user_check
      ignore_errors: yes
      changed_when: false
      failed_when: false

    - name: Create user if it doesn't exist
      command: useradd {{ username }}
      when: user_check.rc != 0

    - name: Add user to group
      user:
        name: {{ username }}
        groups: {{ groupname }}
        append: yes
      when: user_check.rc == 0 and group_check.rc == 0
      become: true
      become_user: ubuntu