
---
- name: Create username in Ubuntu machine
  hosts: 3.87.87.185
  become: yes

  tasks:
    - name: Create user with username
      user:
        name: skills_to_create_the_username_in_machine
        state: present
        shell: /bin/bash

    - name: Set password for the user
      ansible.builtin.shell: |
        echo "skills_to_create_the_username_in_machine:password" | chpasswd

    - name: Add user to sudoers
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        regexp: '^skills_to_create_the_username_in_machine'
        line: 'skills_to_create_the_username_in_machine ALL=(ALL) NOPASSWD:ALL'
        state: present
        validate: /usr/sbin/visudo -cf %s

    - name: Create home directory for the user
      ansible.builtin.file:
        path: /home/skills_to_create_the_username_in_machine
        state: directory
        owner: skills_to_create_the_username_in_machine
        group: skills_to_create_the_username_in_machine
        mode: '0755'