
---
- hosts: 3.87.87.185
  become: true
  tasks:
    - name: Create username in machine
      user:
        name: "{{ default_username }}"
        state: present
      vars:
        default_username: vigil
      ignore_errors: yes
      register: username_created
    - debug:
        msg: "Username {{ default_username }} created successfully"
      when: username_created.changed == true