
---
- hosts: all
  become: true
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: update_result

    - name: Check if any updates are available
      debug:
        msg: "System packages are up to date."
      when: update_result is changed

    - name: Perform system upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result

    - name: Check if system upgrade was successful
      debug:
        msg: "System upgrade completed successfully."
      when: upgrade_result is changed