
---
- name: Update system packages and perform system upgrade
  hosts: all
  become: yes
  
  tasks:
  - name: Update system packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
      state: latest
      
  - name: Perform system upgrade
    apt:
      upgrade: dist
      force_apt_get: yes
      autoremove: yes
      autoclean: yes