
---
- name: Update System Packages and Perform a System Upgrade
  hosts: all
  become: true
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Perform system upgrade
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        cache_valid_time: 3600