---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_os_family == "Debian" # for Debian-based systems
    - name: Update system packages
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat" # for RedHat-based systems
    - name: Perform system upgrade
      apt:
        upgrade: dist
        force_apt_get: yes
      when: ansible_os_family == "Debian" # for Debian-based systems
    - name: Perform system upgrade
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat" # for RedHat-based systems