
---
- name: Update and Upgrade System Packages
  hosts: all
  become: true
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: Update system packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
      
    - name: Perform system upgrade
      apt:
        upgrade: yes
      when: ansible_os_family == "Debian"
      
    - name: Perform system upgrade
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"