
---
- name: Update system packages and perform system upgrade
  hosts: all
  become: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Perform system upgrade
      apt:
        upgrade: yes