
---
- name: Update and Upgrade System Packages
  hosts: all
  gather_facts: false

  tasks:
    - name: Update system packages
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Perform system upgrade
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes