
---
- hosts: all
  become: yes
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Perform system upgrade
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    - name: Update system packages
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Perform system upgrade
      yum:
        name: "*"
        state: latest
        exclude: kernel*
      when: ansible_os_family == "RedHat"