
---
- name: Update System Packages and Perform a System Upgrade
  hosts: all
  become: yes
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Reboot server if kernel is updated
      shell: "test -f /var/run/reboot-required && shutdown -r now || true"
      async: 0
      poll: 0
      ignore_errors: true